/**
 * Network Pulse
 * A simple arp table like tool to see if clients are connected and alive on the network.
 * GitHub: https://www.github.com/0x4248/NetworkPulse
 * Licence: GNU General Public License v3.0
 * By: 0x4248
 *
 * Version generator
 * 
 * This file is used to generate the version.h file which contains 
 * the version number of the program.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_LINE_LENGTH 2000

int main() {
    FILE *file = fopen("Makefile", "r");
    if (file == NULL) {
        printf("Could not open file\n");
        return 1;
    }

    char version[MAX_LINE_LENGTH] = "";
    char patch[MAX_LINE_LENGTH] = "";
    char sublevel[MAX_LINE_LENGTH] = "";

    char line[MAX_LINE_LENGTH];
    while (fgets(line, sizeof(line), file)) {
        if (strncmp(line, "VERSION", 7) == 0) {
            strncpy(version, line + 10, sizeof(version) - 1);
            version[strcspn(version, "\n")] = 0;
        } else if (strncmp(line, "PATCH", 5) == 0) {
            strncpy(patch, line + 8, sizeof(patch) - 1);
            patch[strcspn(patch, "\n")] = 0;
        } else if (strncmp(line, "SUBLEVEL", 8) == 0) {
            strncpy(sublevel, line + 11, sizeof(sublevel) - 1);
            sublevel[strcspn(sublevel, "\n")] = 0;
        }
    }

    fclose(file);

    FILE *version_file = fopen("include/version.h", "w");
    if (version_file == NULL) {
        printf("Could not open file\n");
        return 1;
    } else {
        fprintf(version_file, "// This file is automatically generated buy make genversion\n");
        fprintf(version_file, "#ifndef VERSION_H\n");
        fprintf(version_file, "#define VERSION_H\n\n");
        fprintf(version_file, "#define VERSION \"%s\"\n", version);
        fprintf(version_file, "#define PATCH \"%s\"\n", patch);
        fprintf(version_file, "#define SUBLEVEL \"%s\"\n\n", sublevel);
        fprintf(version_file, "#endif\n");
    }


    return 0;
}