#define CONFIG_DEFAULT_PORT 2002
#define CONFIG_DEFAULT_SERVER_IP "192.168.1.1"
#define CONFIG_PULSE_TABLE 1
#define CONFIG_PULSE_TABLE_FILE_NAME "pulse_table"
#define CONFIG_ENABLE_LOGGING 1
#define CONFIG_SHOW_PULSES 1
#define CONFIG_SAVE_PULSE_LOGS 1
#define CONFIG_PULSE_LOG_FILE_NAME "pulse.log"
